config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs, except: %i[ new edit destroy] do
    member do
      get :confirm
    end
  end
  namespace :admin do
      resources :employees
      resources :posts
      resources :admin_users
      resources :users

      root to: "users#index"
    end
  resources :posts do
    member do
      get :approve
    end 
  end
  devise_for :users, skip: %i[registration]
  root 'static#homepage'  
end

app/views/shared/_admin_dropdown.html.erb
<%= link_to 'Admin Dashbord', admin_root_path %>

app/views/shared/_audit_logs.html.erb
  <li class="nav-item <%= active?(audit_logs_path) %>">
    <%= link_to 'Auditoria', audit_logs_path %>
  </li>

app/views/shared/_employee_items.html.erb
<li class="nav-item <%= active?(posts_path) %>">
  <%= link_to 'Registros', posts_path %>
</li>
<li class="nav-item <%= active?(new_post_path) %>">
  <%= link_to 'Nuevo', new_post_path, id: 'new_post_from_nav' %>
</li>

app/views/shared/_gritter_flash.html.erb
<% if flash[:alert]%>
    <%= js add_gritter(flash[:alert], title: "Sobretime Alerta!", sticky: false, time: 2300) %> 
  <% elsif flash[:error]%>
    <%= js add_gritter(flash[:error], title: "Sobretime Error!", sticky: false, time: 2300) %> 
  <% else%>
    <%= js add_gritter(flash[:notice], title: "Sobretime Notificación!", sticky: false, time: 2300) %>   
<% end %>

app/views/shared/_nav.html.erb
<div class="logo">
<h1>Registro de Horas.</h1>
</div>
<% if current_user%>
  <ul class="custom-nav nav nav-pills">
    <li class="nav-item <%= active?(root_path) %>">
      <%= link_to '', root_path, class: 'glyphicon glyphicon-home' %>
    </li>
    <%= render partial: 'shared/employee_items' if employee?%>

    <%= render partial: 'shared/audit_logs' if admin? %>

    <li class="nav-item dropdown ml-md-auto pull-right">
      <a class="dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown">Opciones<strong class="caret"></strong></a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <%= render partial: 'shared/admin_dropdown' if admin?%>
        <div class="dropdown-divider"></div> 
        <%= link_to 'Cerrar Session', destroy_user_session_path, method: :delete %>
      </div>
    </li>
  </ul>
<% else%>
  <ul class="custom-nav nav nav-pills">
    <li class="nav-item dropdown ml-md-auto pull-right">
      <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Opciones</a>
      <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
        <%= link_to 'Login', new_user_session_path %>
      </div>
    </li>
  </ul>
<% end %>